services:
  - type: web
    name: tutor-saber11
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address 0.0.0.0 --server.port $PORT
    healthCheckPath: /_stcore/health
